config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  root 'static_pages#home'
  get  '/help',       to: 'static_pages#help'
  get  '/about',      to: 'static_pages#about'
  get  '/contact',    to: 'static_pages#contact'
  devise_for :users,  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :show
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    このアプリケーションは<a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>を元に開発されたものです
    by<a href="https://twitter.com/hiraroriP">ひらろり</a> 
  </small>
  <nav>
    <ul>
      <li><%= link_to "TRPG Calendarについて",   about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to "TRPG CALENDAR", user_path(current_user), id: "logo" %>
    <% else %>
      <%= link_to "TRPG CALENDAR", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "ホーム",  user_path(current_user) %></li>
          <li><%= link_to "予定作成",  new_event_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ホーム",  root_path %></li>
          <li><%= link_to "ヘルプ",  help_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body data-turbolinks="false">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>